version: '3.9'

services:
  nginx:
    container_name: crud-nginx
    image: nginx:1.24.0-alpine3.17
    restart: always
    tty: true
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
      - .:/var/www/crud
    ports:
      - '${NGINX_PORT:-80}:80'
    networks:
      crud:
        aliases:
          - crud.local
  crud:
    container_name: crud-php
    build: .docker/php
    image: crud-php
    restart: always
    tty: true
    volumes:
      - .:/var/www/crud
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - crud
  postgres:
    container_name: crud-postgres
    image: postgres:15.3-alpine3.18
    restart: always
    tty: true
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - crud
  keydb:
    container_name: crud-keydb
    image: eqalpha/keydb:latest
    restart: always
    tty: true
    volumes:
      - keydb:/data
    ports:
      - '${KEYDB_PORT:-6379}:6379'
    networks:
      - crud
volumes:
  postgres:
  keydb:
networks:
  crud:

